### ISSUE TITLE
wating for 1.2.2

### ISSUE THREAD

**Issue by veto64** [tripplet/skypeweb4adium#10]
get now the same issue than with my linux/pidgin,
after this update
1.2.2 - Fixes non-Live logins
https://github.com/EionRobb/skype4pidgin/tree/master/skypeweb

all was working again.
please update skypeweb4adium as well

thanks and great work, was waiting for this for years.

**Comment by tripplet** [comment]
Done, see [Release 1.3]( https://github.com/tripplet/skypeweb4adium/releases)
