### ISSUE TITLE
Failed to login

### ISSUE THREAD

**Issue by rodneyrod** [tripplet/skypeweb4adium#11]
Getting the error 'Error: Failed getting PIE value' and keeps asking for a password, don't know how to get any more info out of it though.

**Comment by tripplet** [comment]
Hi, please try the following steps:
1. Are you using the latest version?
2. Try to go through the steps here: https://github.com/EionRobb/skype4pidgin/tree/master/skypeweb#issues
3. Provide some debug info:
https://github.com/tripplet/Adium-Steam-IM/wiki/DebugMessages

**Comment by tripplet** [comment]
There is an issue discussion on the skype4pidgin repository on two factor authentication causing the problem: https://github.com/EionRobb/skype4pidgin/issues/506

**Comment by rodneyrod** [comment]
Issue appears to have resolved itself somehow after I put it in debug mode, no idea what happened there but everything's working fine now. If it occurs again I'll post more details here again.
