### ISSUE TITLE
1.5?

### ISSUE THREAD

**Issue by michael-j-oconnor** [tripplet/skypeweb4adium#13]
Version 1.5 is out, can you update please?

I *think* that with recent changes in Skype, people will need the "alternative auth" support present in the newer release to be able to use this.

Thanks!

**Comment by tripplet** [comment]
I'll try to get to it next week

**Comment by tripplet** [comment]
Sorry to give you bad news but there seem to be some problems building adium using the latest version of xcode (crashes during xib upgrade).
Fixing that will take more time.

**Comment by michael-j-oconnor** [comment]
Building Adium, or building this plugin for Adium?  

Out of curiosity, is this 1.4 port broken for everyone else at this point?  I am basing 1.5 and "alternative auth" as an option off of the recent issues at https://github.com/EionRobb/skype4pidgin/issues , but it looks like it still doesn't work in some cases.

**Comment by tripplet** [comment]
Done, new [Release 1.5](https://github.com/tripplet/skypeweb4adium/releases)
