### ISSUE TITLE
Error: Failed getting PPFT value

### ISSUE THREAD

**Issue by michael-j-oconnor** [tripplet/skypeweb4adium#15]
I started getting this in the past 24 hours.  It looks like a duplicate of:

https://github.com/EionRobb/skype4pidgin/issues/669

**Comment by tripplet** [comment]
Thanks for the info I have a watch on the parent issue and integrate a fix as soon as available.

**Comment by michael-j-oconnor** [comment]
The skype4pidgin people report that backing down to version 1.6 of that plugin fixes this.
However, the skypweb4adium 1.6 is actually based off 1.7. 
So, could you do a 1.7 release based off 1.6?  :)

**Comment by tripplet** [comment]
Should be fixed with the new [release 1.7](https://github.com/tripplet/skypeweb4adium/releases/tag/1.7).

**Comment by michael-j-oconnor** [comment]
1.7 works for me.  Thanks muchly!
