### ISSUE TITLE
No installation or compilation instructions

### ISSUE THREAD

**Issue by rodneyrod** [tripplet/skypeweb4adium#2]
Instructions on how to compile the plugin and all prerequisites would be great to have.

**Comment by 07151129** [comment]
Similarly to [Adium-Steam-IM](https://github.com/tripplet/Adium-Steam-IM):
1. `git submodule init; git submodule update`
2. `cd adium; make`
3. `xcodebuild -configuration Release -project skypeweb4adium.xcodeproj`

**Comment by tripplet** [comment]
Sadly I didn't have much time lately so the repository does not have much to show for.
I'm gladly accepting pull requests :smile:
Build instructions are done.

**Comment by rodneyrod** [comment]
Thanks so much for posting this guys, keep up the good work :)

**Comment by rodneyrod** [comment]
Umm, I'm having issues with compiling Adium on my machine, well, it actually won't compile at all.
Would it be possible to upload a binary release plugin for this?

**Comment by 07151129** [comment]
You could possibly use the frameworks from an already built Adium (see Adium.app/Contents/Frameworks).

**Comment by tripplet** [comment]
@rodneyrod What is the error during the build of adium, because the travis ci build seems to work fine.
https://travis-ci.org/tripplet/skypeweb4adium

**Comment by rodneyrod** [comment]
@tripplet this is the error

The following build commands failed:
	CompileC build/Adium.build/Release-Debug/Adium.build/Objects-normal/x86_64/AWEzvContactManagerRendezvous.o Plugins/Bonjour/libezv/Private\ Classes/AWEzvContactManagerRendezvous.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make: *** [adium] Error 65

**Comment by tripplet** [comment]
Which xcode version are you running, please run these command to make sure you are using the right xcode version (also see https://github.com/vicoapp/vico/issues/3#issuecomment-6857579)
```shell
$ xcodebuild -version
  Xcode 7.1
  Build version 7B91b
```
and 
```shell
$ xcode-select -print-path
  /Applications/Xcode.app/Contents/Developer
```

Maye you can try to build adium in the xcode ui to get a more detailed error.

**Comment by 07151129** [comment]
Try applying this patch before building:
```
diff --git a/Adium.xcodeproj/project.pbxproj b/Adium.xcodeproj/project.pbxproj
index 13eebfb..3c5800c 100644
--- a/Adium.xcodeproj/project.pbxproj
+++ b/Adium.xcodeproj/project.pbxproj
@@ -9957,7 +9957,7 @@
                        );
                        runOnlyForDeploymentPostprocessing = 0;
                        shellPath = /bin/sh;
-                       shellScript = "SOURCE=\"$SRCROOT/build\"\nif [ \"$SOURCE\" != \"$SYMROOT\" ] ; then\n\tif [ -d \"$SOURCE\" ] ; then\n\t\t/bin/rm -Rf \"$SOURCE\"\n\tfi\n\t/bin/ln -fs \"$SYMROOT\" \"$SOURCE\"\nfi";
+                       shellScript = "SOURCE=\"$SRCROOT/build\"";
                };
                F5B17CCE0A16C6AC004AE99E /* ShellScript */ = {
                        isa = PBXShellScriptBuildPhase;
```

**Comment by rodneyrod** [comment]
@07151129 Thanks for the instructions, but how would I go about applying it?
@tripplet I've got 7.1, though I will try and build it with the GUI and get you some more detailed errors.

**Comment by 07151129** [comment]
Check the output of `man git-apply 1`.

**Comment by rodneyrod** [comment]
@07151129 I get the following error when trying to run git apply patch.patch (what I called the file)

>fatal: corrupt patch at line 13

Any idea what might be causing this?

**Comment by 07151129** [comment]
Git is most likely expecting a newline at the end of the patch.

**Comment by rodneyrod** [comment]
Ahh, any idea how to resolve it?
I'm still learning the ins and outs of git.

**Comment by 07151129** [comment]
By adding a newline to the end of the patch using your favourite text editor.

Anyway, the idea of the patch is to remove offending sh script code from "Setup Build Directory" target. In fact, this target itself can probably be safely removed. (Make sure you remove build/ directory before you try building Adium again.)

**Comment by rodneyrod** [comment]
Thing is, I have no line:
>shellScript = "SOURCE=\"$SRCROOT/build\"\nif [ \"$SOURCE\" != \"$SYMROOT\" ] ; then\n\tif [ -d \"$SOURCE\" ] ; then\n\t\t/bin/rm -Rf \"$SOURCE\"\n\tfi\n\t/bin/ln -fs \"$SYMROOT\" \"$SOURCE\"\nfi";

in Adium.xcodeproj/project.pbxproj at all, it's just not there, so I don't know exactly where to edit this.

**Comment by tripplet** [comment]
First working (beta) version is online
https://github.com/tripplet/skypeweb4adium/releases
