### ISSUE TITLE
Skype account suspended when using this plugin in Adium

### ISSUE THREAD

**Issue by Yann-R** [tripplet/skypeweb4adium#3]
Hello,
This plugin is great to add support for Skype in Adium.

Nevertheless, those days I encounter a recurrent problem when using it everyday in Adium:
after a few days, Skype e-mail me that my account has been suspended for security reasons.

I can change my password to reactivate my account, but it appears that if I regularly chat using Skype application, there is no problem, whereas if I use Adium+skyeweb4adium, the problem occurs systematically after a few days.

Any idea?
- Is it related to this port to Adium?
- Is it related to the original SkykeWeb plugin for pigdin? https://github.com/EionRobb/skype4pidgin/
- Is it related to my config?

**Comment by 07151129** [comment]
Have you been reconnecting to skype servers a lot lately?

**Comment by Yann-R** [comment]
Don't know what would be "a lot".
But it's worth mentioning that I use Adium on a laptop, that I can move from office to office during the work day... And then each time Adium wakes up, it reconnect all my account, including Skype with thus plugin.
That meanq several times a day for me... (But there is no problem doing so directly with Skype application).

**Comment by tripplet** [comment]
On my laptop it's working fine, but the laptop is only at home and so does not change it's network status at most once of twice a day when going to sleep or waking up.

Are there any "interesting" debug log messages in Adium: authentication errors, etc..
