### ISSUE TITLE
Extensive CPU Usage

### ISSUE THREAD

**Issue by izotomas** [tripplet/skypeweb4adium#4]
Once I log on, cpu usage for Adium goes from 0 to +100%
Any suggestions?

Adium v1.5.10
OS v10.11.4
plugin v1.2

**Comment by tripplet** [comment]
Difficult to decide what is causing this.
You could try using *Instruments* or view the Adium log for something sticks out.

**Comment by izotomas** [comment]
funny...just found out that Adium was actually 1.5.9...so I switched to 1.5.10 and works fine now

**Comment by tripplet** [comment]
Good to hear
